### ISSUE TITLE
If PHPCR not explicitly enabled, we get error

### ISSUE THREAD

**Issue by dantleech** [symfony-cmf/routing-auto-bundle#109]
If the PHPCR persistence is not explicitly enabled as follows:

```
cmf_routing_auto:
    persistence:
        phpcr:
            enabled: true
```

We get the following error:

```
The service "cmf_routing_auto.adapter.phpcr_odm" has a dependency on a non-existent parameter "cmf_routing_auto.persistence.phpcr.route_basepath". Did you mean one of these:   
  "cmf_routing.dynamic.persistence.phpcr.route_basepaths", "cmf_routing.dynamic.persistence.phpcr.route_basepath", "cmf_routing.dynamic.persistence.phpcr.content_basepath"?
```

We should only load the PHPCR ODM adapter service if the PHPCR thing is enabled.

We can then throw a better error (e.g. choose a persistence strategy..)
