### ISSUE TITLE
[config error] enabled persistence layers using cmf_core config isn't used

### ISSUE THREAD

**Issue by chanakasan** [symfony-cmf/routing-auto-bundle#133]
I installed this bundle today and I started receiving the below error:

```
[Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]                                                       
  The RoutingAUtoBundle requires that you enable one of the persistence layers in your application configuration. See the documentat  
  ion for more information 
```

But I already had the following in my config.yml file.

```
cmf_core:
    persistence:
        phpcr:
            enabled: true

cmf_routing:
    chain:
        routers_by_id:
            router.default: 200
            cmf_routing.dynamic_router: 100
    dynamic:
        persistence:
            phpcr:
                enabled: true
```

I had to use the below config to make the error message go away.

```
cmf_routing_auto:
    persistence:
        phpcr:
            enabled: true
```

According to the documentation I thought the cmf_core persistent layer option will be used by all cmf bundles which means I don't have to do it for each bundle. Am I right?
