### ISSUE TITLE
Allow setting of route attributes for AutoRoute documents

### ISSUE THREAD

**Issue by dantleech** [symfony-cmf/routing-auto-bundle#139]
e.g. to add a host pattern

```
Acme\ForumBundle\Document\Topic:
    uri_schema: /my-forum/{category}/{title}
    attributres:
        hostPattern: foobar.*.dom
    token_providers:
        category: [content_method, { method: getCategoryTitle, slugify: true }]
        title: [content_method, { method: getTitle }] # slugify is true by default
```
