### ISSUE TITLE
AutoRoutes for new objects are not created/persisted when object is created

### ISSUE THREAD

**Issue by awdng** [symfony-cmf/routing-auto-bundle#142]
I am using #2a1ed44

Config

```
Kuoni\BackendBundle\Document\Page\Page:
   uri_schema: /{language}/{title}
   token_providers:
       language: [content_method, { method: getLanguageSlug }]
       title: [content_method, { method: getSlug }]

Kuoni\BackendBundle\Document\Page\Country:
   uri_schema: /{language}/{title}
   token_providers:
       language: [content_method, { method: getLanguageSlug }]
       title: [content_method, { method: getSlug }]

Kuoni\BackendBundle\Document\Page\InsiderStory:
   uri_schema: /{language}/{title}
   token_providers:
       language: [content_method, { method: getLanguageSlug }]
       title: [content_method, { method: getSlug }]

Kuoni\BackendBundle\Document\Page\Project222:
   uri_schema: /{language}/{title}
   token_providers:
       language: [content_method, { method: getLanguageSlug }]
       title: [content_method, { method: getSlug }]

Kuoni\BackendBundle\Document\Page\Region:
   uri_schema: /{language}/{title}
   token_providers:
       language: [content_method, { method: getLanguageSlug }]
       title: [content_method, { method: getSlug }]

Kuoni\BackendBundle\Document\Page\Testimonials:
   uri_schema: /{language}/{title}
   token_providers:
       language: [content_method, { method: getLanguageSlug }]
       title: [content_method, { method: getSlug }]

Kuoni\BackendBundle\Document\Page\Travelogue:
   uri_schema: /{language}/{title}
   token_providers:
       language: [content_method, { method: getLanguageSlug }]
       title: [content_method, { method: getSlug }]

Kuoni\BackendBundle\Document\Page\StaticSummary:
   uri_schema: /{language}/{title}
   token_providers:
       language: [content_method, { method: getLanguageSlug }]
       title: [content_method, { method: getSlug }]

Kuoni\BackendBundle\Document\Page\DynamicSummary:
   uri_schema: /{language}/tag/{tag}
   token_providers:
       language: [content_method, { method: getLanguageSlug }]
       tag: [content_method, { method: getTag }]
```

```
cmf_routing:
    chain:
        routers_by_id:
            cmf_routing.dynamic_router: 20
            router.default: 100

    dynamic:
        enabled: true
        generic_controller: 'Kuoni\FrontendBundle\Controller\PageController::showAction'
        controllers_by_class:
            Kuoni\BackendBundle\Document\Page\Region        : 'Kuoni\FrontendBundle\Controller\PageController::showRegionAction'
            Kuoni\BackendBundle\Document\Page\Country       : 'Kuoni\FrontendBundle\Controller\PageController::showCountryAction'
            Kuoni\BackendBundle\Document\Page\Travelogue    : 'Kuoni\FrontendBundle\Controller\PageController::showTravelogueAction'
            Kuoni\BackendBundle\Document\Page\Home          : 'Kuoni\FrontendBundle\Controller\PageController::showHomeAction'
            Kuoni\BackendBundle\Document\Page\Testimonials  : 'Kuoni\FrontendBundle\Controller\PageController::showTestimonialsAction'
            Kuoni\BackendBundle\Document\Page\Project222    : 'Kuoni\FrontendBundle\Controller\PageController::showProject222Action'
            Kuoni\BackendBundle\Document\Page\InsiderStory  : 'Kuoni\FrontendBundle\Controller\PageController::showInsiderStoryAction'
            Kuoni\BackendBundle\Document\Page\Page          : 'Kuoni\FrontendBundle\Controller\PageController::showPageAction'
            Kuoni\BackendBundle\Document\Page\StaticSummary : 'Kuoni\FrontendBundle\Controller\PageController::showStaticSummaryAction'
        persistence:
            phpcr:
                enabled: true
                route_basepath: /cms/routes

cmf_routing_auto:
    persistence:
        phpcr:
            enabled: true
```

```
class Page implements RouteReferrersInterface
```

This worked on the old version of the Bundle in the same project, but does not work after updating.
What am i missing ?
