### ISSUE TITLE
try to redirect route to 404 when object is removed

### ISSUE THREAD

**Issue by leto3087** [symfony-cmf/routing-auto-bundle#185]
Hi, 
When i remove an object (in this example, it's an Article object), the route associated isn't remove and i have this error 

> Unable to find the controller for path "/url-of-the-article". The route is wrongly configured. 

Can you help me ?

My Config

```
AppBundle\Entity\Article:
    uri_schema: /{thematique}/{title}.html
    conflict_resolver: auto_increment
    defunct_route_handler: leave_redirect
    token_providers:
        thematique: [content_method, { method: getThematiqueTitre }]
        title: [content_method, { method: getTitre }]`

cmf_routing:
    chain:
        routers_by_id:
            cmf_routing.dynamic_router: 100
            router.default: 20
    dynamic:
        enabled: true
        persistence:
            orm: true
        controllers_by_type:
            cmf_routing_auto.redirect: cmf_routing_auto.redirect_controller:redirectAction
        controllers_by_class:
            Symfony\Cmf\Component\Routing\RedirectRouteInterface: cmf_routing.redirect_controller:redirectAction
            AppBundle\Entity\Article: AppBundle:Article:view
```
