### ISSUE TITLE
Locale handling while creating the routes

### ISSUE THREAD

**Issue by damienflament** [symfony-cmf/routing-auto-bundle#200]
Currently, the PhpcrOdmAdapter does not take care of the content document locale when creating the routes for translatable documents.

The `_locale` default is not added to the route defaults. So, when the route content document is mapped to the `contentDocument` request attribute, the request locale remains to the default locale.
I know this can be resolved by using the Lunetics Locale bundle but it rely on the URL, which isn't what I'm looking for.

The '_locale' requirement is not added to the route requirement. So, when an URL is generated from a content document (using the ContentAwareGenerator), the first route always matches regardless the locale of the content.

I resolved those issues using a custom Adapter which simply add the missing default and requirement when creating a route.

But are those behaviors intended ?

**Comment by dbu** [comment]
sounds like it would be useful to have this. question is whether it should always be active or only on demand. @dantleech wdyt about this? should there be a config to enable this? should it be enabled or disabled by default? or does it always make sense to do this (if the doctrine phpcr odm manager has multilang enabled, that is)?

**Comment by dantleech** [comment]
Can it do any harm to add the default? @damienflament 

Otherwise I am curious if something like this would make sense:

```
Symfony\Cmf\Bundle\RoutingAutoBundle\Tests\Resources\Document\Blog:
    definitions:
        frontend:
            uri_schema: /blog/{blog_title}
            defaults:
                _locale: {locale}
    token_providers:
        locale: [locale]
```
