### ISSUE TITLE
Specify action on content rename

### ISSUE THREAD

**Issue by dantleech** [symfony-cmf/routing-auto-bundle#34]
Allow actions to be specified when an autoroute is renamed. e.g.
- **leave_redirect**: When changing the name of post "This post title" to "That post title" a redirect should be created at `/path/this-post-title` to `/path/that-post-title`.
- **remove_headless** When changing the name of post "This post title" to "That post title" the "headless" routes leading up to the old auto route should be deleted.

These options would probably best be placed in the "content_name" section of the configuration:

``` yaml
            content_name:
                # ...
                on_rename: 
                    - [ 'remove_orphans' ]
                    - [ 'leave_redirect', {'option_1': 'foo'} ]
```
