### ISSUE TITLE
RoutingAuto rules should be reusable

### ISSUE THREAD

**Issue by dantleech** [symfony-cmf/routing-auto-bundle#51]
Currently it is necessary to redclare routing rules for each class.

I wonder if we shouldn't seperate schema and mapping?

e.g. currently I have the following:

``` yaml
        Acme\BasicCmsBundle\Document\Page:
            content_path:
                pages:
                    provider: [specified, { path: /cms/routes/page }]
                    exists_action: use
                    not_exists_action: create
            content_name:
                provider: [content_method, { method: getTitle }]
                exists_action: auto_increment
                not_exists_action: create

        Acme\BasicCmsBundle\Document\ContactPage:
            content_path:
                pages:
                    provider: [specified, { path: /cms/routes/page }]
                    exists_action: use
                    not_exists_action: create
            content_name:
                provider: [content_method, { method: getTitle }]
                exists_action: auto_increment
                not_exists_action: create

        Acme\BasicCmsBundle\Document\PostIndex:
            content_path:
                pages:
                    provider: [specified, { path: /cms/routes/page }]
                    exists_action: use
                    not_exists_action: create
            content_name:
                provider: [content_method, { method: getTitle }]
                exists_action: auto_increment
                not_exists_action: create

        Acme\BasicCmsBundle\Document\LatestBlogPost:
            content_path:
                pages:
                    provider: [specified, { path: /cms/routes/page }]
                    exists_action: use
                    not_exists_action: create
            content_name:
                provider: [content_method, { method: getTitle }]
                exists_action: auto_increment
                not_exists_action: create
```

Something like the following would be better:

``` yaml
    schemas:
        page_schema:
            content_path:
                pages:
                    provider: [specified, { path: /cms/routes/page }]
                    exists_action: use
                    not_exists_action: create
            content_name:
                provider: [content_method, { method: getTitle }]
                exists_action: auto_increment
                not_exists_action: create

    mappings:
        Acme\BasicCmsBundle\Document\Page: page_schema
        Acme\BasicCmsBundle\Document\ContactPage: page_schema
        Acme\BasicCmsBundle\Document\PostIndex: page_schema
        Acme\BasicCmsBundle\Document\LatestBlogPost: page_schema
```
