### ISSUE TITLE
Refactor to use URL schema

### ISSUE THREAD

**Issue by dantleech** [symfony-cmf/routing-auto-bundle#67]
Had a long think about routing auto today, and it occurred to me that we could make it alot simpler:

```
cmf_routing_auto:
    mappings:
        Symfony\Cmf\Bundle\RoutingAutoBundle\Tests\Resources\Document\Article:
            url_schema: /test/auto-route/%blog_name%/posts/%article_name%
            providers:
                blog_name:
                        provider: [ content_method, { method_name: "getBlogName" } ]
                        exists_action: use
                        not_exists_action: create
                article_name:
                        provider: [ content_method, { method_name: "getTitle" } ]
                        exists_action: use
                        not_exists_action: create
```

This has the following advantages:
- Its a lot less verbose, alot easier to understand
- It would be easier to do provide a web interface (to allow people to modify URL mappings at runtime) for this than with the current schema
- There is no distinction between "content_name" and "content_path" stacks.
