### ISSUE TITLE
Update existing AutoRoutes

### ISSUE THREAD

**Issue by awdng** [symfony-cmf/routing-auto-bundle#84]
I changed the layout of my routes from this

``` yaml
cmf_routing_auto:
    mappings:
        Kuoni\BackendBundle\Document\Page\Page:
            content_path:
                base_path:
                    provider: [specified, { path: /cms/routes }]
                    exists_action: use
                    not_exists_action: create
                language_path:
                    provider: [specified, { path: de }]
                    exists_action: use
                    not_exists_action: create
                sub_content_path:
                    provider: [content_method, { method: getType }]
                    exists_action: use
                    not_exists_action: create
            content_name:
                provider: [content_method, { method: getTitle }]
                exists_action: [auto_increment, { pattern: -%d }]
                not_exists_action: create
```

to

``` yaml
cmf_routing_auto:
    mappings:
        Kuoni\BackendBundle\Document\Page\Page:
            content_path:
                base_path:
                    provider: [specified, { path: /cms/routes }]
                    exists_action: use
                    not_exists_action: create
                language_path:
                    provider: [specified, { path: de }]
                    exists_action: use
                    not_exists_action: create
            content_name:
                provider: [content_method, { method: getTitle }]
                exists_action: [auto_increment, { pattern: -%d }]
                not_exists_action: create
```

I built a symfony command to remove the route documents, but when i remove the routes the application breaks and routes are not regenerated (which is expected behavior i guess).

So i read that updating the Documents will trigger an update to the Routes, and while the AutoRouteListener is executed when updating a field of the document (like the title/name) the route does not get updated.

What am i missing ?
